apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    app: {{ include "helm.fullname" . }}
spec:
  ports:
  - port: 443
    name: https
    protocol: TCP
    targetPort: https
  selector:
    app: {{ include "helm.fullname" . }}
  type: ClusterIP
