name: Deploy

on:
  workflow_run:
    types:
    - completed
    workflows:
    - Release

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: Get Tag
      shell: bash
      run: |
        VERSION=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}" \
          | jq -r '.head_branch')
        VERSION="${VERSION#v}"

        if [[ "$VERSION" =~ ^(0|[1-9]\d*)+\.(0|[1-9]\d*)\.(0|[1-9]\d*)$ ]]; then
          echo "VERSION=v$VERSION" >> $GITHUB_ENV
        else
          echo "Tag 'v$VERSION' found but not matching v<SEMVER>" >&2
          exit -1
        fi

    - name: Setup Docker Buildx
      if: ${{ env.VERSION }}
      uses: docker/setup-buildx-action@v3

    - name: Build & Push
      if: ${{ env.VERSION }}
      shell: bash
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        REPO_LOWER=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        wget https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/$REPO_NAME-${{ env.VERSION }}.tar.gz

        docker build \
          --build-arg DIST_TAR_BALL=$REPO_NAME-${{ env.VERSION }}.tar.gz \
          --tag ghcr.io/$REPO_LOWER:${{ env.VERSION }} \
          .
        docker push ghcr.io/$REPO_LOWER:${{ env.VERSION }}
        echo "REPO_LOWER=$REPO_LOWER" >> $GITHUB_ENV

    - name: Setup Helm Chart
      if: ${{ env.VERSION }}
      uses: azure/setup-helm@v4.2.0

    - name: Setup Kubernetes Controller
      if: ${{ env.VERSION }}
      uses: azure/k8s-set-context@v4
      with:
        kubeconfig: ${{ secrets.KUBE_CONFIG }}

    - name: Deploy
      if: ${{ env.VERSION }}
      shell: bash
      run: |
        cat <<EOT >> .deployment/helm/values.yaml
        ${{ secrets.HELM_VALUES }}
        EOT
        helm upgrade \
          app .deployment/helm --install \
          --set app.image.tag="${{ env.VERSION }}" \
          --namespace ${{ secrets.KUBE_NAMESPACE }} \
          --set app.image.repository="ghcr.io/${{ env.REPO_LOWER }}"
