name: Release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  release:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Build
      shell: bash
      run: |
        TAG="${GITHUB_REF#refs/tags/}"
        if [[ ! "$TAG" =~ ^v(0|[1-9]\d*)+\.(0|[1-9]\d*)\.(0|[1-9]\d*)$ ]]; then
          echo 'Tag $TAG found but not matching v<SEMVER>' >&2
          exit -1
        fi

        pnpm install
        VERSION="v${GITHUB_REF#refs/tags/v}"
        pnpm build --configuration=production
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        tar -cvzf "code.photo-$VERSION.tar.gz" dist

    - name: Release
      if: ${{ env.VERSION }}
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./code.photo-${{ env.VERSION }}.tar.gz
        tag_name: ${{ env.VERSION }}
        generate_release_notes: true
        prerelease: false
        draft: false
